### ISSUE TITLE
noEmitHelpers compile option in tsconfig.json

### ISSUE THREAD

**Issue by emmanuelroussel** [dherges/ng-hal#2]
Hey,

I started using ng-hal with an Ionic 2 app, but I kept getting this error: `ReferenceError: __extends is not defined`.

After doing a little research, I found out that there was a [similar issue on ng2-smart-table](https://github.com/akveo/ng2-smart-table/issues/26). The temporary fix is to add this as a global script:
```
<script>
    var __extends = (this && this.__extends) || function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
    var __metadata = (this && this.__metadata) || function (k, v) {
        if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
    };
    var __param = (this && this.__param) || function (paramIndex, decorator) {
        return function (target, key) { decorator(target, key, paramIndex); }
    };
    var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
        return new (P || (P = Promise))(function (resolve, reject) {
            function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
            function rejected(value) { try { step(generator.throw(value)); } catch (e) { reject(e); } }
            function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
            step((generator = generator.apply(thisArg, _arguments)).next());
        });
    };
</script>
```
The "real" solution is to compile components with
```
"noEmitHelpers": false
```
in `tsconfig.json` as [implemented on the ng2-smart-table repo](https://github.com/akveo/ng2-smart-table/commit/adb2fbfad24f78d7c4985454b47e40eb6785cea3).

I thought I would let you know and would be happy to make a PR with the fix if you would like to integrate the solution to your repo.

**Comment by dherges** [comment]
Hi Emmanuel,

Thanks for your comment. Yes, of you open up a PR I'd be more than happy.

Cheers, David

**Comment by dherges** [comment]
HI @emmanuelroussel, just letting you know that ``v0.3.0`` is published to npm with the changes you suggested. I hope to continue some more work on this library in late February. If you have more feedback, you're welcome! Cheers!

**Comment by emmanuelroussel** [comment]
@dherges this is weird, I updated the package, but still get the same error. Any idea why this happens?

**Comment by dherges** [comment]
@emmanuelroussel tbh, no. I don't have too much time for this lib atm. I will follow the suggestions made by Wassim Chegham when updating the lib ... see https://github.com/manekinekko/angular-library-starter

**Comment by emmanuelroussel** [comment]
Alright, I will go with the temporary solution posted above for now.
