### ISSUE TITLE
Consider providing instructions on how to build this project

### ISSUE THREAD

**Issue by fdutton** [dherges/ng-hal#41]
As a developer interested in this project, I would like to have a list of requisite tools, their corresponding versions and the relevant processes (e.g., shell commands) needed to build this project so that I can get started understanding how to contribute.

I ask this because I am new to Yarn and I am unsure if I need a specific version or how to invoke Yarn to reproduce a specific version of ng-hal.

**Comment by dherges** [comment]
@fdutton Hi, does #44 give you enough infos?

It includes at least the basics. More details are work-in-progress and may (or may not) change. E.g., the testing strategy: the karma tests are really unit tests. i thought about integration tests also w/ jasmine/karma but it falsifies code coverage. So I will likely move integration tests to the demo app but there is still no common code pattern.

**Comment by fdutton** [comment]
This is perfect. Thank you.
