### ISSUE TITLE
Problem to add module on project

### ISSUE THREAD

**Issue by cgnunezbantics** [dherges/ng-hal#5]
Hello, good library. 
We are newbies in Angular2, we are interesting in add a JWT (AuthHttp) support to lib.
After add changes to operate with ng-hal module:
Own project use "@angular/core": "^2.4.7"
after intall the lib, import the module and start serve
have this error when serve de project.

ERROR in HalModule is not an NgModule
webpack: Failed to compile.
Whats wrong?
Thanks for any help

**Comment by cgnunezbantics** [comment]
We chage declaration in app.module with function HalModule.forRoot()
And have this error:
ERROR in Error encountered resolving symbol values statically. Calling function 'HalModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /home/cgnunez/baseangular/src/app/app.module.ts, resolving symbol AppModule in /home/cgnunez/baseangular/src/app/app.module.ts

**Comment by dherges** [comment]
Hi @cgnunezbantics,

thanks for your report. I'd need to see the code to tell whether this an issue with the library or your application code. From the information you're giving, I cannot tell.

**Comment by dgonsan** [comment]
I think that I have found the same issue, to me it only happens on macos, the same project on Linux works fine.

To reproduce it just create a base angular-cli project, install and import ng-hal module. On Linux it builds without error, on macos it returns the "HalModule is not an NgModule" message.

Detail of the versions used:
@angular/cli: 1.0.0-rc.1                                                                                                                                                                                                                     
node: 7.6.0                                                                                                                                                                                                                                  
os: linux x64                                                                                                                                                                                                                                
@angular/common: 2.4.9                                                                                                                                                                                                                       
@angular/compiler: 2.4.9                                                                                                                                                                                                                     
@angular/core: 2.4.9                                                                                                                                                                                                                         
@angular/forms: 2.4.9                                                                                                                                                                                                                        
@angular/http: 2.4.9                                                                                                                                                                                                                         
@angular/platform-browser: 2.4.9                                                                                                                                                                                                             
@angular/platform-browser-dynamic: 2.4.9                                                                                                                                                                                                     
@angular/router: 3.4.9                                                                                                                                                                                                                       
@angular/cli: 1.0.0-rc.1                                                                                                                                                                                                                     
@angular/compiler-cli: 2.4.9

**Comment by dherges** [comment]
Thanks guys.

Most likely got do with https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735 

https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464#.r5q472glz

Will look at that.

**Comment by dherges** [comment]
Just giving you an update:

was unable to provide a quick solution. Anyway, the build tooling has changed in the mean-up and I will switch to the `ng` cli for the demo application, linking against an `ngc`-compiled library. So, there is a solution coming up ...

**Comment by dherges** [comment]
@dgonsan @cgnunezbantics After quite some time. Has this problem resolved with the new versions that are built in Angular Package Format?
